version: '3'

services:
  binance-stream:
    build: .
    container_name: binance-bbo-stream
    restart: unless-stopped
    ports:
      - "5000:5000"  # HTTP/HTTPS port
    volumes:
      # Mount logs directory to persist logs
      - ./logs:/app/logs
      # Mount certificates
      - ./certs:/app/certs
      # Mount templates and static files for development (optional)
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      # Configuration
      - SYMBOL=btcusdt
      - AUTO_RECONNECT=true
      - MAX_RETRIES=10
      # Web server
      - WEB_ENABLED=true
      - WEB_HOST=0.0.0.0
      - WEB_PORT=5000  # Use port 5000
      # SSL Configuration
      - USE_SSL=true
      - SSL_CERT_PATH=/app/certs/cert.pem
      - SSL_KEY_PATH=/app/certs/key.pem
      # Logging
      - LOG_TO_FILE=true
      - LOG_DIR=/app/logs
      # Enable debugging for troubleshooting
      - DEBUG=true
